version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    target-branch: "main"
    labels:
      - "dependencies"
    groups:
      patternfly:
        applies-to: version-updates
        patterns:
          - "@patternfly/*"
      all:
        applies-to: version-updates
        exclude-patterns:
          - "@patternfly/*"
